
service: python-example-env-vars

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

# you can define service wide environment variables here
  environment:
    FIRST_NAME: "Julio"

functions:
  hello-env-julio:
    handler: handler.hello
  hello-env-benito:
    handler: handler.hello
    environment:
      FIRST_NAME: "Benito"
